//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [Required(ErrorMessage = "This is a required field")]
        public string EventName { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "This is a required field")]
        public string Location { get; set; }
        [Required(ErrorMessage = "This is a required field (dd/mm/yyyy format)")]
        public string Date { get; set; }
        public Nullable<double> TicketFee { get; set; }
    }
}
